Ya Praktikum Sprint 18 - Stage 1 - ewm-stats-service
Alexey-Sutyrin/java-explore-with-me pull request #1
Opened 2024-05-04 19:15 UTC by Alexey-Sutyrin

Ya Praktikum Sprint 18 - Stage 1 - ewm-stats-service

2024-05-05 06:16 UTC, VadimZharkov commented on pom.xml
> +	<dependencies>
Зависимости нужно разместить в помниках отдельных модулей, т.к. они будут разные.
Например модуль клиента статискики -  это не приложение, а просто библиотека, где actuator или PG не нужны, а сейчас из родительского пом они все равно подтянутся.

2024-05-05 06:18 UTC, VadimZharkov commented on statistics/pom.xml
> +    <properties>
А вот свойства лучше вынести в самый корневой pom, т.к. кодировка и версия джавы точно будут одинаковые у всех модулей

2024-05-05 06:22 UTC, VadimZharkov commented on statistics/stats-service/src/main/java/ru/practicum/explorewithme/exception/ErrorHandler.java
> +}
Вместо мапы лучше сделать свой класс ErrorResponse. Сразу будет видна его смысловая нагрузка.

2024-05-05 06:22 UTC, VadimZharkov requested changes
Можно удучшить

2024-05-05 19:07 UTC, Alexey-Sutyrin commented on statistics/stats-service/src/main/java/ru/practicum/explorewithme/exception/ErrorHandler.java
> +}
Спасибо, сделал!

2024-05-05 19:24 UTC, Alexey-Sutyrin commented on statistics/pom.xml
> +    <properties>
Исправил, перенёс.

2024-05-06 09:22 UTC, Alexey-Sutyrin commented on pom.xml
> +	<dependencies>
Исправил, перенёс по модулям dependencies

2024-05-07 06:53 UTC, VadimZharkov approved these changes

2024-05-07 07:06 UTC, Alexey-Sutyrin commented
Ya Praktikum Sprint 18 - Stage 1 - ewm-stats-service - approved by reviewer, merged to Main.

2024-05-07 07:06 UTC, merged