Sprint 18 - Stage 3 - feature_subscriptions addition
Alexey-Sutyrin/java-explore-with-me pull request #13
Opened 2024-05-20 19:06 UTC by Alexey-Sutyrin

Sprint 18 - Stage 3 - feature_subscriptions addition

2024-05-21 07:41 UTC, VadimZharkov reviewed
В dto классах есть совместное употребление 
```
    @NotEmpty
    @NotBlank

```
Достаточно   `@NotBlank`

2024-05-21 07:47 UTC, VadimZharkov reviewed
В дипломной работе для сущностей `@Data` не рекомендуется использовать, т.к. эта аннотация генерит equals и hashCode на основе всех полей.
https://habr.com/ru/companies/haulmont/articles/564682/
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/

2024-05-21 07:49 UTC, VadimZharkov reviewed
часто используется @RequestParam(required = false, defaultValue = "0")
достаточно одного defaultValue

2024-05-21 07:52 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/event/service/EventServiceImpl.java
В данном классе есть дублирующиеся куски кода, 
например
       if (eventUpdate.getAnnotation() != null) {
            oldEvent.setAnnotation(eventUpdate.getAnnotation());
        }
        if (eventUpdate.getCategory() != null) {
            category = categoryService.findCategory(eventUpdate.getCategory());
            oldEvent.setCategory(category);
        }
        if (eventUpdate.getDescription() != null) {
            oldEvent.setDescription(eventUpdate.getDescription());
        }
        if (eventUpdate.getLocation() != null) {
            oldEvent.setLat(eventUpdate.getLocation().getLat());
            oldEvent.setLon(eventUpdate.getLocation().getLon());
        }
        if (eventUpdate.getPaid() != null) {
            oldEvent.setIsPaid(eventUpdate.getPaid());
        }

 дублирующиеся куски кода лучше вынести в приватные методы

2024-05-21 07:56 UTC, VadimZharkov requested changes
По сути в работу перекочевали те же ошибки, что были в прошлый раз.
Нужно внимательно пройтись по всем классам и поправить.

2024-05-22 10:04 UTC, VadimZharkov approved these changes

2024-05-22 13:56 UTC, Alexey-Sutyrin commented
Stage 3 approved !!!

2024-05-22 13:56 UTC, merged