Sprint 18 -Stage 2 - ewm-stats-service - restart check
Alexey-Sutyrin/java-explore-with-me pull request #8
Opened 2024-05-13 12:22 UTC by Alexey-Sutyrin

Sprint 18 -Stage 2 - ewm-stats-service - restart check

2024-05-15 07:01 UTC, VadimZharkov commented on pom.xml
валидация и бд не во всех модулях нужна, поэтому из родительского пом нужно убрать и оставить только в помниках модулей, где данные зависимости действительно нужны

2024-05-15 07:02 UTC, VadimZharkov commented on ewm-service/pom.xml
пустой тег 
    <properties>
    </properties>
нужно убрать

2024-05-15 07:04 UTC, VadimZharkov commented on ewm-service/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-db
закомментированного кода в работе на проверку быть не должно

2024-05-15 07:05 UTC, VadimZharkov commented on ewm-service/src/main/resources/schema.sql
> +  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
более читабильно если добавить отступ у колонок

2024-05-15 08:12 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/controller/CategoryController.java
> +    public List<CategoryDto> findCategories(@RequestParam(required = false, defaultValue = "0") Integer from,
required = false и defaultValue вместе избыточно указывать, достаточно одного defaultValue, оно подразумевает что в эндпоинте значения может и не быть и в этом случае в метод подставляется значение по умолчанию из аннотации.

2024-05-15 08:13 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/dto/CategoryDto.java
> +    @NotBlank
достаточного одного `@NotBlank`

2024-05-15 08:13 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/dto/CategoryDto.java
> +    @NotEmpty
достаточного одного `@NotBlank`

2024-05-15 08:15 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/dto/CategoryMapper.java
> +        for (Category category : categories) {
можно вместо цикла использовать stream().map(). будет выглядеть современнее

2024-05-15 08:17 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/model/Category.java
> +@Data
В дипломной работе для сущностей `@Data` не рекомендуется использовать, т.к. эта аннотация генерит equals и hashCode на основе всех полей.
https://habr.com/ru/companies/haulmont/articles/564682/
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/

2024-05-15 08:19 UTC, VadimZharkov commented on ewm-service/src/main/java/ru.practicum.explorewithme/event/controller/EventController.java
> +    //Private endpoints
Лучше не комментариями разделить на приватные, аднинские и т.д., а разложить по разным классам и пакетам.

2024-05-15 08:23 UTC, VadimZharkov commented on statistics/stats-service/src/main/java/ru/practicum/explorewithme/stats/exception/ErrorHandler.java
Добавить обработку Throwable

2024-05-15 08:23 UTC, VadimZharkov requested changes
Можно улучшить

2024-05-15 10:14 UTC, Alexey-Sutyrin commented on ewm-service/pom.xml
пустые теги из Pom-файлов убрал, спасибо!

2024-05-15 10:20 UTC, Alexey-Sutyrin commented on ewm-service/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-db
Виноват, убрал закомментированный код в этом и других файлах.

2024-05-15 14:30 UTC, Alexey-Sutyrin commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/dto/CategoryDto.java
> +    @NotEmpty
лишний @Not Empty убрал

2024-05-15 14:40 UTC, Alexey-Sutyrin commented on ewm-service/src/main/resources/schema.sql
> +  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
отступы добавил, спасибо!

2024-05-15 14:42 UTC, Alexey-Sutyrin commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/controller/CategoryController.java
> +    public List<CategoryDto> findCategories(@RequestParam(required = false, defaultValue = "0") Integer from,
Спасибо, лишний required=false убран

2024-05-15 17:46 UTC, Alexey-Sutyrin commented on pom.xml
перераспределил повторно, в Pom.xml оставил необходимый минимум.

2024-05-15 18:07 UTC, Alexey-Sutyrin commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/dto/CategoryMapper.java
> +        for (Category category : categories) {
исправил

2024-05-15 18:52 UTC, Alexey-Sutyrin commented on statistics/stats-service/src/main/java/ru/practicum/explorewithme/stats/exception/ErrorHandler.java
Скорректировал

2024-05-15 20:08 UTC, Alexey-Sutyrin commented on ewm-service/src/main/java/ru.practicum.explorewithme/category/model/Category.java
> +@Data
Заменил использование @Data на другие аннотации.

2024-05-15 21:12 UTC, Alexey-Sutyrin commented on ewm-service/src/main/java/ru.practicum.explorewithme/event/controller/EventController.java
> +    //Private endpoints
Разделил на 3 отдельных файла, поименовав их соответственно.

2024-05-16 08:27 UTC, VadimZharkov approved these changes

2024-05-16 09:26 UTC, Alexey-Sutyrin commented
Stage 2 - ewm-stats service -main_svc added + approved

2024-05-16 09:26 UTC, merged